package com.vistas;

import com.dao.DaoCirugia;
import com.dao.DaoCirugiaMedico;
import com.pojos.Cirugia;
import com.pojos.CirugiaMedico;
import com.pojos.Medico;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alfreding0
 */
public class FormCirugia extends javax.swing.JFrame {

    /**
     * Creates new form FormCirugia
     */
    public static Cirugia cirugia = new Cirugia();
    DaoCirugia daoCirugia = new DaoCirugia();

    public static CirugiaMedico cirugiaMedico = new CirugiaMedico();
    DaoCirugiaMedico daoCirugiaMedico = new DaoCirugiaMedico();

    public FormCirugia() {
        initComponents();
        this.setLocationRelativeTo(null);

        this.setFechaInDateChooser();
        this.setHourNowButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupHoral = new javax.swing.ButtonGroup();
        buttonGroupMinuto = new javax.swing.ButtonGroup();
        buttonGroupTurno = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSecretaria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        lblNroSal = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        txtIDDetalle = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombreMedico = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        hora06 = new javax.swing.JRadioButton();
        hora01 = new javax.swing.JRadioButton();
        hora02 = new javax.swing.JRadioButton();
        hora03 = new javax.swing.JRadioButton();
        hora05 = new javax.swing.JRadioButton();
        hora04 = new javax.swing.JRadioButton();
        hora07 = new javax.swing.JRadioButton();
        hora08 = new javax.swing.JRadioButton();
        hora09 = new javax.swing.JRadioButton();
        hora11 = new javax.swing.JRadioButton();
        hora10 = new javax.swing.JRadioButton();
        hora12 = new javax.swing.JRadioButton();
        minEnMedia = new javax.swing.JRadioButton();
        minEnPunto = new javax.swing.JRadioButton();
        turnoAM = new javax.swing.JRadioButton();
        turnoPM = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        txtNroSala = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 39, 57));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("C    I    R    U    G    I    A");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 850, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 80));

        jPanel2.setBackground(new java.awt.Color(50, 89, 128));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Médicos designados");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 370, 39));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 29));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Minuto");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 29));

        txtSecretaria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel2.add(txtSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 190, 29));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Medico________________________________________");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 370, 29));

        jButton1.setBackground(new java.awt.Color(13, 28, 42));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 140, 40));

        jButton2.setBackground(new java.awt.Color(13, 28, 42));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 140, 40));

        jButton3.setBackground(new java.awt.Color(13, 28, 42));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 40));

        jButton4.setBackground(new java.awt.Color(13, 28, 42));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, 40));

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(102, 51, 0));
        txtID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 130, 29));

        tabla.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla.setRowHeight(20);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 370, 230));

        jButton5.setBackground(new java.awt.Color(13, 28, 42));
        jButton5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 140, 40));

        lblNroSal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNroSal.setForeground(new java.awt.Color(255, 255, 255));
        lblNroSal.setText("Nro Sala");
        jPanel2.add(lblNroSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 70, 29));

        jButton6.setBackground(new java.awt.Color(13, 28, 42));
        jButton6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 100, -1));

        txtIDDetalle.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel2.add(txtIDDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 90, 30));

        jButton7.setBackground(new java.awt.Color(13, 28, 42));
        jButton7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Buscar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 80, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Secretaria");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 29));

        txtNombreMedico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel2.add(txtNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 200, 30));

        jButton8.setBackground(new java.awt.Color(13, 28, 42));
        jButton8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Quitar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 150, 40));

        jButton9.setBackground(new java.awt.Color(13, 28, 42));
        jButton9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 204, 204));
        jButton9.setText("Ver Listado");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 370, 40));

        jPanel3.setBackground(new java.awt.Color(26, 72, 107));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroupHoral.add(hora06);
        hora06.setForeground(new java.awt.Color(255, 255, 255));
        hora06.setText("06");
        jPanel3.add(hora06, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        buttonGroupHoral.add(hora01);
        hora01.setForeground(new java.awt.Color(255, 255, 255));
        hora01.setText("01");
        jPanel3.add(hora01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonGroupHoral.add(hora02);
        hora02.setForeground(new java.awt.Color(255, 255, 255));
        hora02.setText("02");
        jPanel3.add(hora02, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        buttonGroupHoral.add(hora03);
        hora03.setForeground(new java.awt.Color(255, 255, 255));
        hora03.setText("03");
        jPanel3.add(hora03, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        buttonGroupHoral.add(hora05);
        hora05.setForeground(new java.awt.Color(255, 255, 255));
        hora05.setText("05");
        jPanel3.add(hora05, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        buttonGroupHoral.add(hora04);
        hora04.setForeground(new java.awt.Color(255, 255, 255));
        hora04.setText("04");
        jPanel3.add(hora04, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        buttonGroupHoral.add(hora07);
        hora07.setForeground(new java.awt.Color(255, 255, 255));
        hora07.setText("07");
        jPanel3.add(hora07, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        buttonGroupHoral.add(hora08);
        hora08.setForeground(new java.awt.Color(255, 255, 255));
        hora08.setText("08");
        jPanel3.add(hora08, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        buttonGroupHoral.add(hora09);
        hora09.setForeground(new java.awt.Color(255, 255, 255));
        hora09.setText("09");
        jPanel3.add(hora09, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        buttonGroupHoral.add(hora11);
        hora11.setForeground(new java.awt.Color(255, 255, 255));
        hora11.setText("11");
        jPanel3.add(hora11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        buttonGroupHoral.add(hora10);
        hora10.setForeground(new java.awt.Color(255, 255, 255));
        hora10.setText("10");
        jPanel3.add(hora10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        buttonGroupHoral.add(hora12);
        hora12.setForeground(new java.awt.Color(255, 255, 255));
        hora12.setText("12");
        jPanel3.add(hora12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        buttonGroupMinuto.add(minEnMedia);
        minEnMedia.setForeground(new java.awt.Color(255, 255, 255));
        minEnMedia.setText("30");
        jPanel3.add(minEnMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, -1));

        buttonGroupMinuto.add(minEnPunto);
        minEnPunto.setForeground(new java.awt.Color(255, 255, 255));
        minEnPunto.setText("00");
        jPanel3.add(minEnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, -1));

        turnoAM.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroupTurno.add(turnoAM);
        turnoAM.setForeground(new java.awt.Color(255, 255, 255));
        turnoAM.setText("AM");
        jPanel3.add(turnoAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 50, -1));

        turnoPM.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroupTurno.add(turnoPM);
        turnoPM.setForeground(new java.awt.Color(255, 255, 255));
        turnoPM.setText("PM");
        jPanel3.add(turnoPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 50, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 10, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 10));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 310, 110));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hora");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 29));
        jPanel2.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 150, 30));

        txtNroSala.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        jPanel2.add(txtNroSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 70, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 850, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.insertarNuevo();
        this.mostrarDetalleMedicoCirugia();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.agregarMedicoADetalle();
        this.mostrarDetalleMedicoCirugia();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.modificarDatos();
        this.mostrarDetalleMedicoCirugia();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.eliminar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        this.copiarFilaACampoDeEdicion();
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.limpiarCampos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new FormSecretaria().setVisible(true);
        FormSecretaria.btnEnviar.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new FormMedico().setVisible(true);
        FormMedico.btnEnviar.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.quitarMedicoDeDetalle();
        this.mostrarDetalleMedicoCirugia();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new FormListaCirugias().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupHoral;
    private javax.swing.ButtonGroup buttonGroupMinuto;
    private javax.swing.ButtonGroup buttonGroupTurno;
    public static javax.swing.JRadioButton hora01;
    public static javax.swing.JRadioButton hora02;
    public static javax.swing.JRadioButton hora03;
    public static javax.swing.JRadioButton hora04;
    public static javax.swing.JRadioButton hora05;
    public static javax.swing.JRadioButton hora06;
    public static javax.swing.JRadioButton hora07;
    public static javax.swing.JRadioButton hora08;
    public static javax.swing.JRadioButton hora09;
    public static javax.swing.JRadioButton hora10;
    public static javax.swing.JRadioButton hora11;
    public static javax.swing.JRadioButton hora12;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    public static com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblNroSal;
    public static javax.swing.JRadioButton minEnMedia;
    public static javax.swing.JRadioButton minEnPunto;
    public static javax.swing.JTable tabla;
    public static javax.swing.JRadioButton turnoAM;
    public static javax.swing.JRadioButton turnoPM;
    public static javax.swing.JTextField txtID;
    public static javax.swing.JTextField txtIDDetalle;
    public static javax.swing.JTextField txtNombreMedico;
    public static javax.swing.JSpinner txtNroSala;
    public static javax.swing.JTextField txtSecretaria;
    // End of variables declaration//GEN-END:variables

//************************CIRUGIA***********************************
    private void insertarNuevo() {
        cirugia = new Cirugia(cirugia.getSecretaria(), jDateChooser.getDate(), this.getHourSelected(), Integer.parseInt(lblNroSal.getText()));
        daoCirugia.insertarCirugia(cirugia);
        txtID.setText(String.valueOf(cirugia.getId()));
    }

    private void modificarDatos() {
        cirugia = new Cirugia(cirugia.getSecretaria(), new Date(), new Date(), Integer.parseInt(lblNroSal.getText()));
        cirugia.setId(Integer.parseInt(txtID.getText()));

        daoCirugia.modificarCirugia(cirugia);
    }

    private void eliminar() {
        cirugia = daoCirugia.buscarCirugiaPorID(Integer.parseInt(txtID.getText()));
        daoCirugia.eliminarCirugia(cirugia);

        this.limpiarCampos();
    }

    private void limpiarCampos() {
        txtID.setText("");
        txtNroSala.getModel().setValue(1);
        txtSecretaria.setText("");
        this.setHourNowButtons();
        jDateChooser.setDate(new Date());

        txtIDDetalle.setText("");
        txtNombreMedico.setText("");
        tabla.setModel(new DefaultTableModel(null, new String[]{"ID", "COD.MEDICO", "NOMBRE COMPLETO"}));
    }

    
    
    
    
//    ************************************DETALLE***************************************************
    private void mostrarDetalleMedicoCirugia() {
        List detalleListaMedicosDesignados = daoCirugiaMedico.getListaDetalleCM_OnlyString(Integer.parseInt(txtID.getText()));

        DefaultTableModel model = new DefaultTableModel(null, new String[]{"ID", "COD.MEDICO", "NOMBRE COMPLETO"});

        detalleListaMedicosDesignados.forEach((obj) -> {
            model.addRow((Object[]) obj);
        });

        tabla.setModel(model);
    }

    private void agregarMedicoADetalle() {
        cirugia = daoCirugia.buscarCirugiaPorID(Integer.parseInt(txtID.getText()));

        cirugiaMedico = new CirugiaMedico(cirugia, cirugiaMedico.getMedico());
        daoCirugiaMedico.insertarCirugiaMedico(cirugiaMedico);
        
        //Limpiar los campos
        txtIDDetalle.setText("");
        txtNombreMedico.setText("");
        cirugia = new Cirugia();
        cirugiaMedico.setMedico(new Medico());
    }

    private void copiarFilaACampoDeEdicion() {
        int fila = tabla.getSelectedRow();
        if (fila > -1) {
            txtIDDetalle.setText(tabla.getValueAt(fila, 0).toString());
            txtNombreMedico.setText(tabla.getValueAt(fila, 2).toString());
        }
    }

    private void quitarMedicoDeDetalle() {
        daoCirugiaMedico.eliminarCirugiaMedico(daoCirugiaMedico.findById(Integer.parseInt(txtIDDetalle.getText())));
        
        //Limpiar los campos
        txtIDDetalle.setText("");
        txtNombreMedico.setText("");
        cirugia = new Cirugia();
        cirugiaMedico.setMedico(new Medico());
    }

    //este metodo ya no se ocupa, porque lo reemplamos por otro
    private void setFechaInTxtFecha() {
        DateFormat inFormat = new SimpleDateFormat("dd/MM/yyyy"); //Otro formato E, dd MMM yyyy
        inFormat.setTimeZone(TimeZone.getTimeZone("America/La_Paz"));
        Date fechaCirugia = new Date();
        //txtFecha.setText(inFormat.format(fechaCirugia));
    }
    
    private void setFechaInDateChooser(){
        jDateChooser.setDate(new Date());
    }

    private void setHourNowButtons() {
        DateFormat inFormat = new SimpleDateFormat("HH:mm");
        inFormat.setTimeZone(TimeZone.getTimeZone("America/La_Paz"));
        Date horaCirugia = new Date();
        String horaFormateado = inFormat.format(horaCirugia);
        FormCirugia.setHourInButtons(horaFormateado.substring(0, 2), horaFormateado.substring(3, 4));
    }

    private String hora = null, minuto = null, turno = null;

    private boolean isSelectedHourMinuteTurn() {
        boolean selectedAll = true;

        if (hora01.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "01";
            } else if (turnoPM.isSelected()) {
                hora = "13";
            } else {
                selectedAll = false;
            }
        } else if (hora02.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "02";
            } else if (turnoPM.isSelected()) {
                hora = "14";
            } else {
                selectedAll = false;
            }
        } else if (hora03.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "03";
            } else if (turnoPM.isSelected()) {
                hora = "15";
            } else {
                selectedAll = false;
            }
        } else if (hora04.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "04";
            } else if (turnoPM.isSelected()) {
                hora = "16";
            } else {
                selectedAll = false;
            }
        } else if (hora05.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "05";
            } else if (turnoPM.isSelected()) {
                hora = "17";
            } else {
                selectedAll = false;
            }
        } else if (hora06.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "06";
            } else if (turnoPM.isSelected()) {
                hora = "18";
            } else {
                selectedAll = false;
            }
        } else if (hora07.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "07";
            } else if (turnoPM.isSelected()) {
                hora = "19";
            } else {
                selectedAll = false;
            }
        } else if (hora08.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "08";
            } else if (turnoPM.isSelected()) {
                hora = "20";
            } else {
                selectedAll = false;
            }
        } else if (hora09.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "09";
            } else if (turnoPM.isSelected()) {
                hora = "21";
            } else {
                selectedAll = false;
            }
        } else if (hora10.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "10";
            } else if (turnoPM.isSelected()) {
                hora = "22";
            } else {
                selectedAll = false;
            }
        } else if (hora11.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "11";
            } else if (turnoPM.isSelected()) {
                hora = "23";
            } else {
                selectedAll = false;
            }
        } else if (hora12.isSelected()) {
            if (turnoAM.isSelected()) {
                hora = "00";
            } else if (turnoPM.isSelected()) {
                hora = "12";
            } else {
                selectedAll = false;
            }
        } else {
            selectedAll = false;
        }

        if (minEnPunto.isSelected()) {
            minuto = "00";
        } else if (minEnMedia.isSelected()) {
            minuto = "30";
        } else {
            selectedAll = false;
        }

        return selectedAll;
    }

    private String getHour() {
        if (this.isSelectedHourMinuteTurn()) {
            return hora + ":" + minuto;
        } else {
            return null;
        }
    }

    private Date getHourSelected() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
            Date hourFormated = sdf.parse(getHour() + ":00");
            return hourFormated;
        } catch (ParseException ex) {
            Logger.getLogger(FormCirugia.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public static void setHourInButtons(String hour, String minute){
        if (hour.equals("01") || hour.equals("1")) {
            hora01.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("02") || hour.equals("2")) {
            hora02.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("03") || hour.equals("3")) {
            hora03.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("04") || hour.equals("4")) {
            hora04.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("05") || hour.equals("5")) {
            hora05.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("06") || hour.equals("6")) {
            hora06.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("07") || hour.equals("7")) {
            hora07.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("08") || hour.equals("8")) {
            hora08.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("09") || hour.equals("9")) {
            hora09.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("10")) {
            hora10.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("11")) {
            hora11.setSelected(true);
            turnoAM.setSelected(true);
        } else if (hour.equals("12")) {
            hora12.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("13")) {
            hora01.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("14")) {
            hora02.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("15")) {
            hora03.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("16")) {
            hora04.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("17")) {
            hora05.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("18")) {
            hora06.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("19")) {
            hora07.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("20")) {
            hora08.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("21")) {
            hora09.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("22")) {
            hora10.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("23")) {
            hora11.setSelected(true);
            turnoPM.setSelected(true);
        } else if (hour.equals("00")) {
            hora12.setSelected(true);
            turnoAM.setSelected(true);
        }

        if ((minute.equals("00")) || (Integer.parseInt(minute) < 3)) {
            minEnPunto.setSelected(true);
        } else if ((minute.equals("30")) || (Integer.parseInt(minute) >= 3)) {
            minEnMedia.setSelected(true);
        }
    }
}
