package com.vistas;

import com.dao.DaoCirugia;
import com.dao.DaoCirugiaMedico;
import com.pojos.Cirugia;
import com.pojos.CirugiaMedico;
import com.util.HibernateUtil;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SpinnerModel;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alfreding0
 */
public class FormListaCirugias extends javax.swing.JFrame {

    /**
     * Creates new form FormCirugia
     */
    public static Cirugia cirugia = new Cirugia();
    DaoCirugia daoCirugia = new DaoCirugia();

    public FormListaCirugias() {
        initComponents();
        this.setLocationRelativeTo(null);

        this.mostrarListaCirugias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 39, 57));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LISTADO DE CIRUGIAS PLANIFICADOS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 590, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 80));

        jPanel2.setBackground(new java.awt.Color(50, 89, 128));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(13, 28, 42));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Mostrar Detalles");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 160, 40));

        tabla.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla.setRowHeight(20);
        jScrollPane1.setViewportView(tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 510, 230));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.mostrarDetalleEnFormCirugia();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

//************************CIRUGIA***********************************
    private void mostrarListaCirugias() {
        Session session = HibernateUtil.getSessionFactory().openSession();
//        String hql = "FROM Cirugia";
//        Query query = session.createQuery(hql);
//        List<Cirugia> listaCirugias = query.list();
        
        List lista = daoCirugia.getListaCirugias_OnlyString();

        DefaultTableModel model = new DefaultTableModel(null, new String[]{"ID", "FECHA", "HORA", "NROSALA", "SECRETARIA"});

        lista.forEach((fila) -> { model.addRow( (Object[]) fila); });

        tabla.setModel(model);
        
        session.close();
    }

    private void mostrarDetalleEnFormCirugia() {
        int fila = tabla.getSelectedRow();
        if (fila > -1) {
            try {
                FormCirugia.txtID.setText(tabla.getValueAt(fila, 0).toString());
                
                Date fecha = new SimpleDateFormat("yyyy-MM-dd").parse(tabla.getValueAt(fila, 1).toString());
                FormCirugia.jDateChooser.setDate(fecha);
                
                String hora = tabla.getValueAt(fila, 2).toString();
                FormCirugia.setHourInButtons(hora.substring(0, 2), hora.substring(3, 5));
                
                FormCirugia.txtNroSala.getModel().setValue(Integer.parseInt(tabla.getValueAt(fila, 3).toString()));
                
                FormCirugia.txtSecretaria.setText(tabla.getValueAt(fila, 4).toString());
                
                DaoCirugiaMedico daoCirugiaMedico = new DaoCirugiaMedico();
                List lista = daoCirugiaMedico.getListaDetalleCM_OnlyString(Integer.parseInt(tabla.getValueAt(fila, 0).toString()));
                
                DefaultTableModel model = new DefaultTableModel(null, new String[]{"ID", "COD.MEDICO", "NOMBRE COMPLETO"});
                
                lista.forEach((obj) -> { model.addRow( (Object[]) obj ); });
                
                FormCirugia.tabla.setModel(model);
                
                int idCirugia = Integer.parseInt(tabla.getValueAt(fila, 0).toString());
                FormCirugia.cirugia.setSecretaria(daoCirugia.buscarCirugiaPorID(idCirugia).getSecretaria());
            } catch (ParseException ex) {
                Logger.getLogger(FormListaCirugias.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
