package com.pojos;
// Generated Jul 2, 2022 3:13:56 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CirugiaMedico generated by hbm2java
 */
@Entity
@Table(name = "cirugia_medico",
         catalog = "db_clinica"
)
public class CirugiaMedico implements java.io.Serializable {

    private Integer id;
    private Cirugia cirugia;
    private Medico medico;

    public CirugiaMedico() {
    }

    public CirugiaMedico(Cirugia cirugia, Medico medico) {
        this.cirugia = cirugia;
        this.medico = medico;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cirugia_id", nullable = false)
    public Cirugia getCirugia() {
        return this.cirugia;
    }

    public void setCirugia(Cirugia cirugia) {
        this.cirugia = cirugia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medico_id", nullable = false)
    public Medico getMedico() {
        return this.medico;
    }

    public void setMedico(Medico medico) {
        this.medico = medico;
    }

}
