package com.pojos;
// Generated Jul 25, 2022 12:39:37 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CirugiaMedico generated by hbm2java
 */
@Entity
@Table(name = "cirugia_medico",
         schema = "public"
)
public class CirugiaMedico implements java.io.Serializable {

    private int id;
    private Cirugia cirugia;
    private Medico medico;

    public CirugiaMedico() {
    }

    public CirugiaMedico(Cirugia cirugia, Medico medico) {
        this.cirugia = cirugia;
        this.medico = medico;
    }
        
    public CirugiaMedico(int id, Cirugia cirugia, Medico medico) {
        this.id = id;
        this.cirugia = cirugia;
        this.medico = medico;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cirugia_id", nullable = false)
    public Cirugia getCirugia() {
        return this.cirugia;
    }

    public void setCirugia(Cirugia cirugia) {
        this.cirugia = cirugia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medico_id", nullable = false)
    public Medico getMedico() {
        return this.medico;
    }

    public void setMedico(Medico medico) {
        this.medico = medico;
    }

}
