package com.pojos;
// Generated Jul 25, 2022 12:39:37 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cirugia generated by hbm2java
 */
@Entity
@Table(name = "cirugia",
         schema = "public"
)
public class Cirugia implements java.io.Serializable {

    private int id;
    private Secretaria secretaria;
    private Date fecha;
    private Date hora;
    private int nroSala;
    private Set<CirugiaMedico> cirugiaMedicos = new HashSet<CirugiaMedico>(0);

    public Cirugia() {
    }

    public Cirugia(int id, Secretaria secretaria, Date fecha, Date hora, int nroSala) {
        this.id = id;
        this.secretaria = secretaria;
        this.fecha = fecha;
        this.hora = hora;
        this.nroSala = nroSala;
    }

    public Cirugia(Secretaria secretaria, Date fecha, Date hora, int nroSala) {
        this.secretaria = secretaria;
        this.fecha = fecha;
        this.hora = hora;
        this.nroSala = nroSala;
    }

    public Cirugia(int id, Secretaria secretaria, Date fecha, Date hora, int nroSala, Set<CirugiaMedico> cirugiaMedicos) {
        this.id = id;
        this.secretaria = secretaria;
        this.fecha = fecha;
        this.hora = hora;
        this.nroSala = nroSala;
        this.cirugiaMedicos = cirugiaMedicos;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "secretaria_id", nullable = false)
    public Secretaria getSecretaria() {
        return this.secretaria;
    }

    public void setSecretaria(Secretaria secretaria) {
        this.secretaria = secretaria;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 13)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "hora", nullable = false, length = 15)
    public Date getHora() {
        return this.hora;
    }

    public void setHora(Date hora) {
        this.hora = hora;
    }

    @Column(name = "nro_sala", nullable = false)
    public int getNroSala() {
        return this.nroSala;
    }

    public void setNroSala(int nroSala) {
        this.nroSala = nroSala;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cirugia")
    public Set<CirugiaMedico> getCirugiaMedicos() {
        return this.cirugiaMedicos;
    }

    public void setCirugiaMedicos(Set<CirugiaMedico> cirugiaMedicos) {
        this.cirugiaMedicos = cirugiaMedicos;
    }

}
