package com.pojos;
// Generated Jul 2, 2022 3:13:56 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Secretaria generated by hbm2java
 */
@Entity
@Table(name = "secretaria",
         catalog = "db_clinica"
)
public class Secretaria implements java.io.Serializable {

    private Integer id;
    private String nombreCompleto;
    private String celular;
    private String direccion;
    private Set<Cirugia> cirugias = new HashSet<Cirugia>(0);

    public Secretaria() {
    }

    public Secretaria(String nombreCompleto, String celular, String direccion) {
        this.nombreCompleto = nombreCompleto;
        this.celular = celular;
        this.direccion = direccion;
    }

    public Secretaria(String nombreCompleto, String celular, String direccion, Set<Cirugia> cirugias) {
        this.nombreCompleto = nombreCompleto;
        this.celular = celular;
        this.direccion = direccion;
        this.cirugias = cirugias;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "nombre_completo", nullable = false, length = 50)
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }

    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }

    @Column(name = "celular", nullable = false, length = 12)
    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    @Column(name = "direccion", nullable = false, length = 200)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "secretaria")
    public Set<Cirugia> getCirugias() {
        return this.cirugias;
    }

    public void setCirugias(Set<Cirugia> cirugias) {
        this.cirugias = cirugias;
    }

}
